### ISSUE TITLE
Why CPP is slower than Python?

### ISSUE THREAD

**Issue by FantasyJXF** [BIGBALLON/pytorch_cpp#3]
I tested the pretrained ResNet34 with original model and jit traced model, with 400 images, the image preprocess of Python and C++ is the same, which is just like the way you did.

On my Mac.
Python costs 34 seconds, CPU usage >90%.
C++ costs 73 seconds, CPU usage < 40%.
why?   why?   why?

**Comment by BIGBALLON** [comment]
@FantasyJXF  PLZ check [discuss](https://discuss.pytorch.org/t/my-libtorch-binary-built-from-source-is-slower-than-official-binary/44503/7) and [issue19106](https://github.com/pytorch/pytorch/issues/19106) for more details.

**Comment by FantasyJXF** [comment]
Looks like that's a normal problem

**Comment by BIGBALLON** [comment]
@FantasyJXF maybe

**Comment by FantasyJXF** [comment]
Did you test the performance of the libtorch with Pytorch? 

What should it be?

**Comment by BIGBALLON** [comment]
@FantasyJXF I think caffe model is the better choice

**Comment by FantasyJXF** [comment]
Do you mean convert the PyTorch model to caffemodel with ONNX or sth?

**Comment by BIGBALLON** [comment]
@FantasyJXF yeap, lots of projects and companies convert PyTorch model to Caffe model by ONNX or their own tools.

**Comment by FantasyJXF** [comment]
Many thanks
